### ISSUE TITLE
Audio Support for Tape Storage

### ISSUE THREAD

**Issue by austeregrim** [d99kris/nopeos#1]
I know this isn't really an issue, and I don't know how else to suggest this. I'm sorry, I know this is the wrong way to do this.
But is there any way we can get audio card support in the kernel for writing programs out, and loading back in. For example to write to a "tape" (actual tape, or virtual via mp3 player/phone recorder), and to similarly play back from said tape to load.

I'm sure this was done through hardware means in "classic" computers. But would be a game changer to actually have NopeOS as a thing that would be usable for people like me to learn the history of classic computers through real world simulations.

**Comment by austeregrim** [comment]
Further investigation on how tinybasic supported "to tape", or more accurately how old computers wrote to tape. It sounds like it was keyboard inputs were intrinsically "audible signals", which could be recorded to tapes, computer character outputs were the same keyboard "sounds". Which makes the capability near impossible to recreate. (Probably easier to implement a file reading function.)

I think you'd have to keep listening on the audio in device for the "keyboard input sounds" to be able to interpret this at any time, as tinybasic doesn't natively support input other than keyboard. Conversely, all characters output to the screen would also have to be output to the audio out device for when the LIST command is given at the point of "recording".

I'll close this issue. But I hope you get to see it, as I am really happy that you've given me a stepping stone for historical education about computing that I would have missed otherwise. And someone has seen your project, played with it, and enjoyed it. :-D

**Comment by d99kris** [comment]
> But I hope you get to see it, as I am really happy that you've given me a stepping stone for historical education about computing that I would have missed otherwise. And someone has seen your project, played with it, and enjoyed it. :-D

Thank you, it's great to hear :-)
