### ISSUE TITLE
USB Boot

### ISSUE THREAD

**Issue by yuppox** [d99kris/nopeos#3]
Hi,

I tried the ISO on a VM and it worked. I can't get it to boot from a USB drive on a physical computer. Have you tried booting from USB? Is there a certain method I should use to make the USB drive bootable?

Thanks!

**Comment by d99kris** [comment]
Hi @yuppox - good catch! I think at the time I put together Nope OS I only tested physical boot with a CD. I've now built an img disk image which you can [download here](https://github.com/d99kris/nopeos/releases/download/v0.1/nopeos-0.1.img) and write to a USB drive using for example `dd` or a GUI program like [balenaEtcher](https://www.balena.io/etcher).

I will eventually update the source code repository with script changes for building the img file, I just need to clean them up a little bit.

I'll proceed to close this issue, but feel free to re-open it if you have any follow-up questions.

**Comment by d99kris** [comment]
With the above commit the script changes for building the img file has been added.

**Comment by yuppox** [comment]
Thank you!
